name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17.2

    - name: Build
      run: go build -v ./...

    - name: Test qrcode
      run: go test -v ./...

    - name: Test writer/standard
      run: cd ./writer/standard && go test -v ./...
      
    - name: Test writer/terminal
      run: ./writer/terminal && go test -v ./...
